"""Migration smoke test against a real Postgres (skipped when none is reachable)."""

from __future__ import annotations

import pytest
from alembic import command

from better_resume.settings import get_settings

from .db_utils import alembic_config


def test_alembic_upgrade_and_check(migrated_database: str, monkeypatch: pytest.MonkeyPatch) -> None:
    # Alembic's env.py resolves the URL through Settings, so restore the ambient value.
    monkeypatch.setenv("BR_DATABASE_URL", migrated_database)
    get_settings.cache_clear()

    config = alembic_config()
    command.downgrade(config, "base")
    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected when models drift from head
