"""P2-T4: rebuild the ASR fixture audio from scratch (no binary blobs in git).

The wav is synthesized (edge-tts voice, fixed script text) and downsampled to 16 kHz mono,
so any machine can regenerate the input for the real-machine probes. PINNED_SHA256 guards
against silent fixture drift: --check exits 2 when the local bytes differ from the pin
(regeneration may legitimately produce different bytes -- then update the pin consciously
and note it in the evidence).

Usage:
  uv run python scripts/make_fixture_audio.py --check              # no network
  uv run python scripts/make_fixture_audio.py --generate           # needs network (edge-tts)
  uv run python scripts/make_fixture_audio.py --check --file PATH  # check any file
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import pathlib

TARGET = pathlib.Path("../../data/audio/p1c-multi-sentence-16k.wav")
SCRIPT_TEXT = (
    "第一句，我负责过订单系统的重构。"
    "第二句，接口响应时间从八百毫秒降到了两百毫秒。"
    "第三句，我们用熔断和限流保证了稳定性。"
)
PINNED_SHA256 = "8bcd672121ad0d441cf20af9e765e0a7fb42620a5e1c2ce9f2f077f3bbbca7dd"


def sha256_of(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def check(path: pathlib.Path) -> int:
    if not path.exists():
        print(f"missing fixture: {path} (run with --generate first, needs network)")
        return 2
    digest = sha256_of(path)
    if digest != PINNED_SHA256:
        print(f"sha256 mismatch: got {digest}, pinned {PINNED_SHA256}")
        return 2
    print(f"sha256 ok: {digest}")
    return 0


def generate(path: pathlib.Path) -> int:
    import edge_tts
    import numpy as np
    import soundfile as sf

    tmp_mp3 = path.with_suffix(".tmp.mp3")

    async def synth() -> None:
        await edge_tts.Communicate(SCRIPT_TEXT, "zh-CN-XiaoxiaoNeural").save(str(tmp_mp3))

    asyncio.run(synth())
    data, rate = sf.read(tmp_mp3, dtype="float32")
    if data.ndim > 1:
        data = data.mean(axis=1)
    target_rate = 16000
    n_target = int(len(data) * target_rate / rate)
    resampled = np.interp(np.linspace(0, len(data) - 1, n_target), np.arange(len(data)), data)
    sf.write(path, (resampled * 32767).astype("int16"), target_rate, subtype="PCM_16")
    tmp_mp3.unlink()
    digest = sha256_of(path)
    print(f"generated: {path} ({n_target / target_rate:.1f}s) sha256={digest}")
    if digest != PINNED_SHA256:
        print(
            "note: regenerated bytes differ from the pin (edge-tts output is not "
            "deterministic). The fixture is still valid; update PINNED_SHA256 consciously "
            "if the evidence must stay byte-comparable."
        )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify sha256, no network")
    parser.add_argument("--generate", action="store_true", help="synthesize the fixture")
    parser.add_argument("--file", type=pathlib.Path, default=TARGET)
    args = parser.parse_args()
    if args.generate:
        return generate(args.file)
    return check(args.file)


if __name__ == "__main__":
    raise SystemExit(main())
